 Comparing Numbers

In [9]:
#max number or greatest
a=(92, 392, 4456, 89742)
print(max(a))

89742


In [10]:
#min number or smallest
a=(92, 392, 4456, 89742)
print(min(a))

92


ascending or descending

In [20]:
#ascending
import numpy as np
arr= np.array([1,7,3,4])
arr.sort()
print(arr)




[1 3 4 7]


In [27]:
#descending
import numpy as np

arr = np.array([2, 8, 7, 4])
arr_sorted = arr.argsort()[::-1]
print(arr[arr_sorted])

[8 7 4 2]


shifting numbers

In [28]:
import numpy as np
arr = np.array([2, 8, 7, 4])
# Swap first and last elements
arr[0], arr[3] = arr[3], arr[0]
print(arr) 


[4 8 7 2]
